site_name: "mkdocs-latest-git-tag-plugin"

repo_url: https://github.com/seapagan/mkdocs-latest-git-tag-plugin
repo_name: mkdocs-latest-git-tag-plugin
copyright: © 2023 Grant Ramsay (Seapagan)

theme:
  name: material
  language: en
  features:
    - navigation.footer
    - navigation.expand

extra:
  social:
    - icon: material/web
      link: https://www.gnramsay.com
    - icon: fontawesome/brands/github
      link: https://github.com/seapagan
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gnramsay_dev

plugins:
  - search
  - latest-git-tag

markdown_extensions:
  - admonition
  - attr_list

nav:
  - Home: index.md
  - Development:
      - Contributing: development/contributing.md
      - Documentation: development/documentation.md
